export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-900 py-12 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-white mb-8">
          Terms of Service
        </h1>
        
        <div className="prose prose-invert">
          <p className="text-gray-400 mb-6">
            Last Updated: {new Date().toLocaleDateString()}
          </p>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              1. Acceptance of Terms
            </h2>
            <p className="text-gray-300">
              By accessing and using ChefAI ("the Service"), you accept and agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              2. Description of Service
            </h2>
            <p className="text-gray-300">
              ChefAI is an AI-powered recipe generation service that analyzes photos of food ingredients and suggests recipes. The Service uses artificial intelligence to identify ingredients and create recipe recommendations.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              3. User Responsibilities
            </h2>
            <ul className="list-disc pl-6 text-gray-300 space-y-2">
              <li>Provide accurate information about ingredients</li>
              <li>Use the Service only for lawful purposes</li>
              <li>Do not attempt to reverse engineer AI models</li>
              <li>Verify food safety before cooking</li>
              <li>Follow proper food handling and cooking procedures</li>
            </ul>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              4. AI-Generated Content Disclaimer
            </h2>
            <p className="text-gray-300 mb-4">
              All recipes are generated by artificial intelligence and should be used as suggestions only. While we strive for accuracy:
            </p>
            <ul className="list-disc pl-6 text-gray-300 space-y-2">
              <li>Always verify ingredient compatibility and food safety</li>
              <li>Adjust cooking times and temperatures for your equipment</li>
              <li>Check for allergens and dietary restrictions</li>
              <li>We are not responsible for cooking results or food safety</li>
            </ul>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              5. Affiliate Disclosure
            </h2>
            <p className="text-gray-300">
              ChefAI participates in affiliate programs including Instacart. We may earn a commission when you purchase ingredients through our recommended retailers. This does not affect the price you pay.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              6. Limitation of Liability
            </h2>
            <p className="text-gray-300">
              ChefAI is provided "as is" without warranty of any kind. We are not responsible for:
            </p>
            <ul className="list-disc pl-6 text-gray-300 space-y-2">
              <li>Recipe quality or cooking results</li>
              <li>Food safety or allergic reactions</li>
              <li>Any damages arising from use of the Service</li>
              <li>Third-party content or services</li>
            </ul>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              7. Changes to Terms
            </h2>
            <p className="text-gray-300">
              We may update these terms at any time. Continued use of the Service constitutes acceptance of updated terms.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              8. Contact
            </h2>
            <p className="text-gray-300">
              For questions about these Terms, contact us at: support@chefai.app
            </p>
          </section>
        </div>
        
        <div className="mt-12">
          <a 
            href="/"
            className="text-emerald-400 hover:text-emerald-300"
          >
            ← Back to ChefAI
          </a>
        </div>
      </div>
    </div>
  )
}

